version: '3.5'

services:

  web:
    build: ./webapp
    image: webapp
    container_name: webapp
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - redis
    volumes:
      - /root/flaskapp/app:/app

  redis:
    image: redis:3.2.11
    container_name: redis
